export const CART_ADD_ITEM_PERSONAL_DETAILS = 'CART_ADD_ITEM_PERSONAL_DETAILS';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const CART_SAVE_SOCIAL_MEDIA_SUCCESS = 'CART_SAVE_MEDIA_SUCCESS';
export const CART_SAVE_SOCIAL_MEDIA_REQUEST = 'CART_SAVE_MEDIA_REQUEST';
export const CART_SAVE_SOCIAL_MEDIA_FAIL = 'CART_SAVE_MEDIA_FAIL';
